Griboedoff/verify pack
ForNeVeR/Fenrir pull request #61
Opened 2021-11-11 16:09 UTC by Griboedoff

Implementation of verify-pack. closes #41

2021-11-27 13:11 UTC, ForNeVeR requested changes
Overall: a good work, with some minor issues.

2021-11-27 13:11 UTC, ForNeVeR commented on Fenrir/Tools.fs
> +    member reader.GetBigEndian() : int =
_(Minor)_ Let's rename this to `ReadBigEndianInt`? Otherwise, it's confusing (I genuinely was confused by this name while reviewing this).

2021-11-28 10:35 UTC, Griboedoff commented on Fenrir/PackVerification.fs
> +            [| Encoding.ASCII.GetBytes($"{objectTypeName} {dataStream.Length}\u0000")
do i need to make this change in output printing or it's ok?

2021-11-28 12:13 UTC, ForNeVeR commented on Fenrir/PackVerification.fs
> +            [| Encoding.ASCII.GetBytes($"{objectTypeName} {dataStream.Length}\u0000")
Ideally, the output should be culture-invariant, too. But it's not a major issue.

2021-11-28 12:25 UTC, ForNeVeR approved these changes

2021-11-28 12:31 UTC, merged

2021-11-28 12:31 UTC, ForNeVeR commented
Thanks!